version: "3.8"

networks:
  laravel303:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: laravel303_nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_APP_HOST=${APP_DOMAIN_NAME}
      - WEBSOCKET_APP_HOST=${WEBSOCKET_DOMAIN_NAME}
    ports:
      - "38003:8001"
    volumes:
      - ../src:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./sites-enabled/* /etc/nginx/sites-enabled/
      - ../.docker_configs/certs:/etc/nginx/certs
    depends_on:
      - php
      - mysql
    networks:
      - laravel303
  redis:
    image: redis
    container_name: laravel303_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "37913:6379"
    networks:
      - laravel303
  redisinsight:
    image: redislabs/redisinsight
    container_name: laravel303_redisinsight
    restart: unless-stopped
    volumes:
      - ../redis:/var/lib/redis
    ports:
      - "37903:8001"
    networks:
      - laravel303
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel303_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 104857600
      MEMORY_LIMIT: 2G
      # MAX_EXECUTION_TIME: 600
    ports:
      - "38103:80"
    networks:
      - laravel303

  mysql:
    image: mysql
    container_name: laravel303_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "38503:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      MYSQL_DATABASE: laravel
      MYSQL_USER: tlc_app_2
      MYSQL_PASSWORD: DLTedTfrVzYbrYv9
    command: mysqld --log-bin-trust-function-creators=1
    networks:
      - laravel303

  phpmyadmin_001a:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_001a
    restart: unless-stopped
    depends_on:
      - mysql_001a
    environment:
      PMA_HOST: mysql_001a
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 104857600
      MEMORY_LIMIT: 2G
      # MAX_EXECUTION_TIME: 600
    ports:
      - "38203:80"
    networks:
      - laravel303

  mysql_001a:
    image: mysql
    container_name: mysql_001a
    restart: unless-stopped
    tty: true
    ports:
      - "38603:3306"
    volumes:
      - ../mysql_001a:/var/lib/mysql_001a
    environment:
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      MYSQL_DATABASE: laravel
      MYSQL_USER: tlc_app_2
      MYSQL_PASSWORD: DLTedTfrVzYbrYv9
    command: mysqld --log-bin-trust-function-creators=1
    networks:
      - laravel303

  phpmyadmin_002a:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_002a
    restart: unless-stopped
    depends_on:
      - mysql_002a
    environment:
      PMA_HOST: mysql_002a
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 104857600
      MEMORY_LIMIT: 2G
      # MAX_EXECUTION_TIME: 600
    ports:
      - "38303:80"
    networks:
      - laravel303

  mysql_002a:
    image: mysql
    container_name: mysql_002a
    restart: unless-stopped
    tty: true
    ports:
      - "38703:3306"
    volumes:
      - ../mysql_002a:/var/lib/mysql_002a
    environment:
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      MYSQL_DATABASE: laravel
      MYSQL_USER: tlc_app_2
      MYSQL_PASSWORD: DLTedTfrVzYbrYv9
    command: mysqld --log-bin-trust-function-creators=1
    networks:
      - laravel303
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel303_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ../src:/var/www/app
      - ../.docker_configs/certs:/etc/nginx/certs
    ports:
      - "39003:9000"
    networks:
      - laravel303
